[project]
name = "python-code-writer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nileshtn", email = "tjnilesh55@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.4.2",
    "langchain-ollama>=1.1.0",
    "langgraph>=1.2.12",
]

[project.scripts]
python-code-writer = "python_code_writer:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
